baseurl = "/"
languageCode = "en-us"
title = "Carsten's blog"
theme = "hugo-lithium-theme"
googleAnalytics = "UA-108049545-1"
disqusShortname = "cbds-netlify-com"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/behrica/"
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/carsten_behring"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/behrica/"


[params]
    description = "Carsten's data science blog"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.11.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml","clojure"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.1"

#    [params.logo]
#    url = "logo.png"
#    width = 50
#    height = 50
#    alt = "Logo"

